### ISSUE TITLE
Not starting on VPS

### ISSUE THREAD

**Issue by Kadiya99** [EvamariaTG/EvaMaria#198]
When I try 
"python3 bot.py"
This error showing

Traceback (most recent call last):
  File "bot.py", line 12, in <module>
    from database.ia_filterdb import Media
  File "/root/evamaria/database/ia_filterdb.py", line 10, in <module>
    from info import DATABASE_URI, DATABASE_NAME, COLLECTION_NAME, USE_CAPTION_FILTER
  File "/root/evamaria/info.py", line 15, in <module>
    API_ID = int(environ['API_ID', "17526358"])
  File "/usr/lib/python3.7/os.py", line 675, in __getitem__
    value = self._data[self.encodekey(key)]
  File "/usr/lib/python3.7/os.py", line 753, in encode
    raise TypeError("str expected, not %s" % type(value).__name__)
TypeError: str expected, not tuple

[info for info.py.txt](https://github.com/EvamariaTG/EvaMaria/files/8192810/info.for.info.py.txt)

check the info.py file

**Comment by subinps** [comment]
Invalid
