### ISSUE TITLE
Error Index

### ISSUE THREAD

**Issue by mirrorclone** [EvamariaTG/EvaMaria#23]
2021-11-01T06:17:11.423223+00:00 app[worker.1]: 06:17:11 AM - 230 - pyrogram.dispatcher - dispatcher - ERROR - invalid literal for int() with base 10: 'ModdedCentral'

2021-11-01T06:17:11.423234+00:00 app[worker.1]: Traceback (most recent call last):

2021-11-01T06:17:11.423235+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 217, in handler_worker

2021-11-01T06:17:11.423235+00:00 app[worker.1]:     await handler.callback(self.client, *args)

2021-11-01T06:17:11.423236+00:00 app[worker.1]:   File "/app/plugins/index.py", line 40, in index_files

2021-11-01T06:17:11.423236+00:00 app[worker.1]:     await index_files_to_db(int(lst_msg_id), int(chat), msg, bot)

2021-11-01T06:17:11.423236+00:00 app[worker.1]: ValueError: invalid literal for int() with base 10: 'apkchannel'

**Comment by mirrorclone** [comment]
@subinps  at dec time, the manager of the mahesh media search bot was indexing channels that were open to everyone. yours.he wants me to be his admin on the bot.

**Comment by subinps** [comment]
You must update your bot with latest changes.
This error is already fixed.

**Comment by mirrorclone** [comment]
@subinps thanks
