### ISSUE TITLE
issue when indexing files in pyrogram v2

### ISSUE THREAD

**Issue by iamLiquidX** [EvamariaTG/EvaMaria#266]
log , hope this helps in debugging.

2022-08-10T17:48:20.862813+00:00 app[worker.1]: 05:48:20 PM - 253 - pyrogram.dispatcher - dispatcher - ERROR - Telegram says: [420 FLOOD_WAIT_X] - A wait of 40 seconds is required (caused by "messages.EditMessage")
2022-08-10T17:48:20.862824+00:00 app[worker.1]: Traceback (most recent call last):
2022-08-10T17:48:20.862825+00:00 app[worker.1]:   File "/app/plugins/index.py", line 156, in index_files_to_db
2022-08-10T17:48:20.862825+00:00 app[worker.1]:     await msg.edit_text(
2022-08-10T17:48:20.862826+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 2777, in edit_text
2022-08-10T17:48:20.862827+00:00 app[worker.1]:     return await self._client.edit_message_text(
2022-08-10T17:48:20.862827+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 80, in edit_message_text
2022-08-10T17:48:20.862828+00:00 app[worker.1]:     r = await self.invoke(
2022-08-10T17:48:20.862828+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
2022-08-10T17:48:20.862828+00:00 app[worker.1]:     r = await self.session.invoke(
2022-08-10T17:48:20.862829+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
2022-08-10T17:48:20.862829+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
2022-08-10T17:48:20.862830+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
2022-08-10T17:48:20.862830+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2022-08-10T17:48:20.862830+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-08-10T17:48:20.862831+00:00 app[worker.1]:     raise getattr(
2022-08-10T17:48:20.862831+00:00 app[worker.1]: pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 40 seconds is required (caused by "messages.EditMessage")
2022-08-10T17:48:20.862831+00:00 app[worker.1]: 
2022-08-10T17:48:20.862832+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2022-08-10T17:48:20.862832+00:00 app[worker.1]: 
2022-08-10T17:48:20.862833+00:00 app[worker.1]: Traceback (most recent call last):
2022-08-10T17:48:20.862833+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-08-10T17:48:20.862833+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-08-10T17:48:20.862834+00:00 app[worker.1]:   File "/app/plugins/index.py", line 49, in index_files
2022-08-10T17:48:20.862834+00:00 app[worker.1]:     await index_files_to_db(int(lst_msg_id), chat, msg, bot)
2022-08-10T17:48:20.862834+00:00 app[worker.1]:   File "/app/plugins/index.py", line 183, in index_files_to_db
2022-08-10T17:48:20.862834+00:00 app[worker.1]:     await msg.edit(f'Error: {e}')
2022-08-10T17:48:20.862835+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 2777, in edit_text
2022-08-10T17:48:20.862835+00:00 app[worker.1]:     return await self._client.edit_message_text(
2022-08-10T17:48:20.862835+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 80, in edit_message_text
2022-08-10T17:48:20.862835+00:00 app[worker.1]:     r = await self.invoke(
2022-08-10T17:48:20.862836+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
2022-08-10T17:48:20.862836+00:00 app[worker.1]:     r = await self.session.invoke(
2022-08-10T17:48:20.862836+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
2022-08-10T17:48:20.862836+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
2022-08-10T17:48:20.862837+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
2022-08-10T17:48:20.862837+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2022-08-10T17:48:20.862837+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-08-10T17:48:20.862838+00:00 app[worker.1]:     raise getattr(
2022-08-10T17:48:20.862838+00:00 app[worker.1]: pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 40 seconds is required (caused by "messages.EditMessage")
2022-08-10T17:48:20.407198+00:00 app[worker.1]: 05:48:20 PM - 182 - plugins.index - index - ERROR - Telegram says: [420 FLOOD_WAIT_X] - A wait of 40 seconds is required (caused by "messages.EditMessage")
2022-08-10T17:48:20.407209+00:00 app[worker.1]: Traceback (most recent call last):
2022-08-10T17:48:20.407209+00:00 app[worker.1]:   File "/app/plugins/index.py", line 156, in index_files_to_db
2022-08-10T17:48:20.407210+00:00 app[worker.1]:     await msg.edit_text(
2022-08-10T17:48:20.407211+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 2777, in edit_text
2022-08-10T17:48:20.407211+00:00 app[worker.1]:     return await self._client.edit_message_text(
2022-08-10T17:48:20.407211+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 80, in edit_message_text
2022-08-10T17:48:20.407212+00:00 app[worker.1]:     r = await self.invoke(
2022-08-10T17:48:20.407226+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
2022-08-10T17:48:20.407226+00:00 app[worker.1]:     r = await self.session.invoke(
2022-08-10T17:48:20.407227+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
2022-08-10T17:48:20.407227+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
2022-08-10T17:48:20.407227+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
2022-08-10T17:48:20.407228+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2022-08-10T17:48:20.407228+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-08-10T17:48:20.407228+00:00 app[worker.1]:     raise getattr(
2022-08-10T17:48:20.407229+00:00 app[worker.1]: pyrogram.errors.exceptions.flood_420.FloodWait: Telegram says: [420 FLOOD_WAIT_X] - A wait of 40 seconds is required (caused by "messages.EditMessage")
2022-08-10T17:54:15.263941+00:00 app[worker.1]: 05:54:15 PM - 253 - pyrogram.dispatcher - dispatcher - ERROR - Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")
2022-08-10T17:54:15.263952+00:00 app[worker.1]: Traceback (most recent call last):
2022-08-10T17:54:15.263953+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
2022-08-10T17:54:15.263953+00:00 app[worker.1]:     await handler.callback(self.client, *args)
2022-08-10T17:54:15.263954+00:00 app[worker.1]:   File "/app/plugins/pm_filter.py", line 557, in cb_handler
2022-08-10T17:54:15.263954+00:00 app[worker.1]:     await query.message.edit_text(
2022-08-10T17:54:15.263955+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/types/messages_and_media/message.py", line 2777, in edit_text
2022-08-10T17:54:15.263955+00:00 app[worker.1]:     return await self._client.edit_message_text(
2022-08-10T17:54:15.263956+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/messages/edit_message_text.py", line 80, in edit_message_text
2022-08-10T17:54:15.263957+00:00 app[worker.1]:     r = await self.invoke(
2022-08-10T17:54:15.263957+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
2022-08-10T17:54:15.263957+00:00 app[worker.1]:     r = await self.session.invoke(
2022-08-10T17:54:15.263958+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 361, in invoke
2022-08-10T17:54:15.263958+00:00 app[worker.1]:     return await self.send(query, timeout=timeout)
2022-08-10T17:54:15.263959+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/session/session.py", line 331, in send
2022-08-10T17:54:15.263959+00:00 app[worker.1]:     RPCError.raise_it(result, type(data))
2022-08-10T17:54:15.263959+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
2022-08-10T17:54:15.263960+00:00 app[worker.1]:     raise getattr(
2022-08-10T17:54:15.263960+00:00 app[worker.1]: pyrogram.errors.exceptions.bad_request_400.MessageNotModified: Telegram says: [400 MESSAGE_NOT_MODIFIED] - The message was not modified because you tried to edit it using the same content (caused by "messages.EditMessage")

@adi-code22

**Comment by iamLiquidX** [comment]
only happens with user submitted indexing request.
